linters:
  enable:
    - errcheck
    - gosec
    - govet
    - staticcheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: benchmarks/
      linters:
        - errcheck
    - path: examples/
      linters:
        - gosec
